USE EDA_ASSIGNMENT_5;

# SELECTING AND VIEWING ALL DATA OF THE TABLE
SELECT * FROM samplefakerdata2;

# TASKS AS PER ASSIGNMENT-5

# QUERY 1 : TOTAL SALES (FINDING TOTAL SALES AMOUNT (QUANTITY * PRICE PER UNIT) PER REGION)
SELECT REGION,FORMAT(SUM(QUANTITY*PRICE_PER_UNIT),2) AS TOTAL_SALES_AMOUNT
FROM samplefakerdata2
GROUP BY REGION;

# QUERY 2 : TOP PRODUCTS (RETRIEVE THE TOP 5 PRODUCTS BY TOTAL SALES(QUANTITY*PRICE_PER_UNIT))
SELECT PRODUCT_ID,FORMAT(SUM(QUANTITY*PRICE_PER_UNIT),2) AS TOTAL_SALES_AMOUNT
FROM samplefakerdata2
GROUP BY PRODUCT_ID
ORDER BY PRODUCT_ID DESC
LIMIT 5;

# QUERY 3 : MONTHLY SALES : CALCULATE TOTAL SALES FOR EACH MONTH
SELECT monthname(PURCHASE_DATE) AS MONTH_,
FORMAT(SUM(QUANTITY*PRICE_PER_UNIT),2) AS TOTAL_SALES_AMOUNT
FROM samplefakerdata2
GROUP BY monthname(PURCHASE_DATE)
ORDER BY FIELD((MONTH_),'JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER');

# QUERY 4 : CUSTOMER PURCHASE ANALYSIS : RETRIEVE THE TOTAL AMOUNT SPENT BY EACH CUSTOMER
SELECT CUSTOMER_NAME, FORMAT(SUM(QUANTITY*PRICE_PER_UNIT),2) AS TOTAL_AMOUNT_SPENT
FROM samplefakerdata2
GROUP BY customer_name;

# QUERY 5 : PRODUCT SALES BY REGION : LIST THE TOTAL SALES OF EACH PRODUCT PER REGION.
SELECT REGION,PRODUCT_ID,FORMAT(SUM(QUANTITY*PRICE_PER_UNIT),2) AS TOTAL_SALES
FROM samplefakerdata2
GROUP BY REGION,PRODUCT_ID
ORDER BY FIELD((REGION),'NORTH','SOUTH','EAST','WEST'),PRODUCT_ID;